name: custom_multi_search
description: A customizable multi-select dropdown widget with search functionality for Flutter applications using MobX state management.
version: 1.0.6
homepage: https://github.com/pavan-kumar-mannem/selestro
repository: https://github.com/pavan-kumar-mannem/selestro
issue_tracker: https://github.com/pavan-kumar-mannem/selestro/issues

license: MIT

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.3.0+1
  flutter_mobx: ^2.2.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  mobx_codegen: ^2.4.0
  json_annotation: ^4.8.1

flutter:
  uses-material-design: true
